export const ROUTES = {
  landing: '/',
  auth: '/continue',
  dashboard: '/dashboard',
  problems: '/problems',
  problemDetail: (slug = ':slug') => `/problems/${slug}`,
  learningPaths: '/learning-paths',
  learningPathDetail: (slug = ':slug') => `/learning-paths/${slug}`,
  contests: '/contests',
  contestDetail: (id = ':id') => `/contests/${id}`,
  leaderboard: '/leaderboard',
  profile: (username = ':username') => `/profile/${username}`,
  myProfile: '/profile/me',
  notifications: '/notifications',
  search: '/search',
  settings: '/settings',
}
