import {GoogleGenerativeAI} from "@google/generative-ai";import User from "../users/user.model.js";import Problem from "../problems/problem.model.js";import {env} from "../../config/env.js";
const limit=Number(process.env.AI_DAILY_LIMIT||10);
function model(){if(!env.geminiApiKey)throw Object.assign(new Error("GEMINI_API_KEY is not configured"),{statusCode:503});return new GoogleGenerativeAI(env.geminiApiKey).getGenerativeModel({model:process.env.GEMINI_MODEL||"gemini-1.5-flash"});}
async function quota(userId){const u=await User.findById(userId);if(!u)throw Object.assign(new Error("User not found"),{statusCode:401});const day=new Date().toISOString().slice(0,10);if(u.aiUsage?.day!==day){u.aiUsage={day,count:0};}if(u.role==="student"&&u.aiUsage.count>=limit)throw Object.assign(new Error(`Daily AI limit reached (${limit})`),{statusCode:429});u.aiUsage.count+=1;await u.save();}
async function ask(userId,prompt){await quota(userId);const r=await model().generateContent(prompt);return r.response.text();}
export async function hint({userId,problemTitle,code,stage=1}){const text=await ask(userId,`You are Full Prep's coding tutor. Problem: ${problemTitle||"coding problem"}. Student code:\n${code||"No code yet"}\nGive hint stage ${stage} only. Stage 1 is conceptual, 2 is more specific, 3 is pseudocode. Never provide complete code or final answer.`);return {stage:Number(stage),hint:text,hasMore:Number(stage)<3}}
export async function debug({userId,problemTitle,code,failedTestCase,errorOutput}){const text=await ask(userId,`You are a strict coding debugger. Problem: ${problemTitle||""}. Code:\n${code||""}\nFailed test:\n${failedTestCase||""}\nError/output:\n${errorOutput||""}\nExplain the bug and guide the fix without giving complete corrected code.`);return {issue:text}}
export async function complexity({userId,code}){const text=await ask(userId,`Analyze this code's time and space complexity. Return concise JSON with keys time, space, explanation. Code:\n${code||""}`);try{return JSON.parse(text.replace(/```json|```/g,"").trim())}catch{return {time:"Unknown",space:"Unknown",explanation:text}}}
export async function explain({userId,code}){const text=await ask(userId,`Explain this code clearly for a student. Do not rewrite it. Code:\n${code||""}`);return {explanation:text}}
export async function chat({userId,message,history=[]}){const text=await ask(userId,`You are Full Prep's coding study partner. Answer educationally and do not provide full solutions unless explicitly appropriate. Conversation:\n${history.map(x=>`${x.role}: ${x.content}`).join("\n")}\nStudent: ${message}`);return {role:"assistant",content:text}}
