import { OAuth2Client } from "google-auth-library";
import dotenv from "dotenv";

dotenv.config();

const clientId = process.env.GOOGLE_CLIENT_ID;
const clientSecret = process.env.GOOGLE_CLIENT_SECRET;

if (!clientId) {
  console.warn("GOOGLE_CLIENT_ID is not configured.");
}

if (!clientSecret) {
  console.warn("GOOGLE_CLIENT_SECRET is not configured.");
}

const oauthClient = new OAuth2Client(clientId, clientSecret);

/**
 * Verify a Google Sign-In ID token.
 *
 * Kept for compatibility with the existing auth system.
 */
export const verifyGoogleToken = async (idToken) => {
  if (!idToken) {
    throw new Error("Google ID token is required");
  }

  if (!clientId) {
    throw new Error("GOOGLE_CLIENT_ID is not configured");
  }

  const ticket = await oauthClient.verifyIdToken({
    idToken,
    audience: clientId,
  });

  return ticket.getPayload();
};

/**
 * Exchange a Google authorization code for tokens.
 *
 * The code is generated by:
 *
 * google.accounts.oauth2.initCodeClient()
 *
 * and returned through its callback.
 */
export const exchangeGoogleCode = async (code) => {
  if (!code) {
    throw new Error("Google authorization code is required");
  }

  if (!clientId) {
    throw new Error("GOOGLE_CLIENT_ID is not configured");
  }

  if (!clientSecret) {
    throw new Error("GOOGLE_CLIENT_SECRET is not configured");
  }

  const { tokens } = await oauthClient.getToken({
    code,

    /**
     * For the popup authorization-code flow,
     * Google sends the code to the browser callback
     * and the backend performs the server-side exchange.
     *
     * The redirect URI must match the value used by
     * the Google OAuth client configuration.
     */
    redirect_uri: process.env.GOOGLE_REDIRECT_URI || undefined,
  });

  if (!tokens?.id_token) {
    throw new Error("Google did not return an ID token");
  }

  const ticket = await oauthClient.verifyIdToken({
    idToken: tokens.id_token,
    audience: clientId,
  });

  return {
    payload: ticket.getPayload(),
    tokens,
  };
};
